version: "3.5"

services:
  gdr_app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
      MAILGUN_API_DOMAIN: "${MAILGUN_API_DOMAIN}"
    ports:
      - 8567:8567
    volumes:
      - .:/go/src/github.com/arkrozycki/go-dead-rabbit
      - go-modules:/go/pkg/mod
    working_dir: /go/src/github.com/arkrozycki/go-dead-rabbit
    restart: on-failure
    depends_on:
      - gdr_rabbitmq

  gdr_rabbitmq:
    build:
      context: ./docker/rabbitmq
    hostname: gdr_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "health-check"]
      interval: 10s
      timeout: 5s
      retries: 5

  gdr_mongodb:
    image: mongo:4.2
    container_name: gdr_mongodb
    restart: always
    environment:
      # - AUTH=yes
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=go-dead-rabbit
    volumes:
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'
    command: mongod #--logpath=/dev/null # --quiet
volumes:
  go-modules:
