version: "3.5"

services:
  gdr_app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
      MAILGUN_API_DOMAIN: "${MAILGUN_API_DOMAIN}"
    volumes:
      - .:/go/src/github.com/arkrozycki/go-dead-rabbit
      - go-modules:/go/pkg/mod
    working_dir: /go/src/github.com/arkrozycki/go-dead-rabbit
    restart: on-failure
    depends_on:
      - gdr_rabbitmq

  gdr_rabbitmq:
    build:
      context: ./docker/rabbitmq
    hostname: gdr_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "health-check"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  go-modules:
